[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"
showSidebarNavigation = true
#enforceSerializableSessionState = true

[server]
headless = true
runOnSave = false
showEmailPrompt = false
